# Generated by Django 4.2.5 on 2023-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('deviceModel', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('serial', models.CharField(max_length=50)),
            ],
        ),
    ]
